### ISSUE TITLE
Deleting Data Error

### ISSUE THREAD

**Issue by PhilDiscuss** [dmzx/Travis-BBcode#1]
Display Name:
Travis BBcode
Clean Name:
dmzx/travisbbcode
Description:
This Extension will add a new BBcode for Travis Build Status.
Version:
1.0.1
Homepage:
http://www.dmzx-web.net
Release Time:
2015-11-22
Licence:
GPL-2.0

http://prntscr.com/debyeh

**Comment by dmzx** [comment]
Upload all files from 1.0.1 version and try again.
